Fix a bug introduced by the TGen 1.0.0 update.
The bug was that we were using the wrong Analysis class in measure
mode:

AttributeError: 'Analysis' object has no attribute 'add_torctl_file'